name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1 Checkout repo
    - uses: actions/checkout@v4

    # 2 Setup Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # 3 Install dependecies
    - name: Install Sphinx dependencies
      run: |
        pip install sphinx sphinx_rtd_theme sphinxcontrib-matlabdomain myst-parser

    # 4 Build documentation
    - name: Build Sphinx documentation
      run: |
        cd docs
        make html

    # 5 Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: _build/html
        force_orphan: true
